image: alpine/latest
packages:
  - docker
  - ruby
  - ruby-dev
  - util-linux-login
sources:
  - https://git.sr.ht/~teymour/eldemite
secrets:
  - 5c0c5bc0-2b3a-4185-923d-ac4a9c0a6a09
  - fe9881cc-e007-4f7c-93df-ee0a3ce63895
tasks:
  - deploy: |
      sudo bash /home/build/eldemite/deploy-srht.sh
