image: debian/stable
packages:
  - ruby
  - ruby-dev
  - pkg-config
  - libssl-dev
  - cmake
  - clang
  - sqlite3
  - libsqlite3-dev
  - curl
sources:
  - https://git.sr.ht/~teymour/eldemite
secrets:
  - 5c0c5bc0-2b3a-4185-923d-ac4a9c0a6a09
  - 442be735-05de-423c-8250-6c3df985c252
tasks:
  - install_rust: |
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain nightly
      source "$HOME/.cargo/env"
  - test: |
      cd eldemite
      source "$HOME/.cargo/env"
      cargo test
  - install_docker: |
      curl -sSL https://get.docker.com/ | sh
  - deploy: |
      cd /home/build/eldemite
      sudo gem install kamal
      export GEM_HOME="$(ruby -e 'puts Gem.user_dir')"
      export PATH="$PATH:$GEM_HOME/bin"

      cat > ~/docker-wrapper << 'EOF'
      #!/bin/bash
      sudo docker "$@"
      EOF
      chmod +x ~/docker-wrapper

      mkdir -p ~/bin
      ln -sf ~/docker-wrapper ~/bin/docker
      export PATH="$HOME/bin:$PATH"

      set +x
      . /home/build/.set_secret_env_vars
      set -x

      kamal deploy
