[package]
name = "main"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
rand = "0.8.5"
rocket = { version = "0.5.1", features = ["uuid"] }
db = { path = "../db" }
email = { path = "../email" }
diesel = { version = "2.2.4", features = ["chrono", "r2d2"] }
uuid = { version = "1.11.0", features = ["v7"] }
maud = { version = "0.26.0", features = ["rocket"] }
url = "2.5.3"
addr = "0.15.6"
either = "1.13.0"
reqwest = "0.12.9"
qrcode = "0.14.1"
regex = "1.11.1"
serde_json = "1.0.133"
serde = { version = "1.0.217", features = ["derive"] }
argon2 = "0.5.3"
good_lp = { version = "1.11.0", default-features = false, features = ["highs"] }
lazy_static = "1.5.0"
arbitrary = { version = "1.4.1", features = ["derive"] }

[dev-dependencies]
insta = "1.42.0"
lazy_static = "1.5.0"
serde_urlencoded = "0.7.1"
